### ISSUE TITLE
Formats on Terraform files

### ISSUE THREAD

**Issue by timfallmk** [fd/language-hcl#2]
The files that are marked as being HCL files include `tf` files. This would overwrite the different format of Terraform files.

**Comment by fd** [comment]
@timfallmk what other formats can a `tf` file have?

**Comment by samirageb** [comment]
Not completely sure if this is relevant anymore, but Terraform's default extensions are .tf & .tfvars

.tfvars are purely condensed key/value pairs that specify default values for variables defined elsewhere. The file supports whitespace, newlines, comments, etc. but a typical file would just have many lines that look like this:

default_region = "us-east-1"
variable1 = "45412315645123"
variable_default2 = "foo"

**Comment by timfallmk** [comment]
@fd Sorry, my original comment was that `tf` and `tfvars` files were being marked by the extension as HCL and therefore getting incorrectly highlighted.

**Comment by fd** [comment]
@timfallmk I'm going to close this issue for now.

**Comment by timfallmk** [comment]
@fd The user-side solution is to remove `.tf` and `.tfvars` from the supported file list in the plugin config.
